trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'terraform-sp-devops'  # Cambia esto por tu Service Connection

steps:
  - task: UseTerraform@0
    inputs:
      terraformVersion: '1.5.0'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: '$(azureServiceConnection)'
      # Aquí puedes agregar configuración para backend si usas remoto (opcional)

  - task: TerraformTaskV4@4
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: '$(azureServiceConnection)'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: '$(azureServiceConnection)'
      args: '-auto-approve'
